import { Product } from 'components/product-item/product-item'

export const productInput: Product = {
  items: [
    { img: `chair_1.jpg` },
    { img: `chair_2.jpg` },
    { img: `chair_3.jpg` },
    { img: `chair_4.jpg` },
    { img: `chair_5.jpg` },
    { img: `chair_6.jpg` },
    { img: `chair_7.jpg` },
    { img: `chair_8.jpg` },
    { img: `chair_9.jpg` },
    { img: `chair_10.jpg` },
    { img: `chair_11.jpg` },
    { img: `chair_12.jpg` },
    { img: `chair_13.jpg` },
    { img: `chair_14.jpg` },
    { img: `chair_15.jpg` },
    { img: `chair_16.jpg` },
    { img: `chair_17.jpg` },
    { img: `chair_18.jpg` },
    { img: `chair_19.jpg` },
    { img: `chair_20.jpg` },
    { img: `chair_21.jpg` },
    { img: `chair_22.jpg` },
    { img: `chair_23.jpg` },
    { img: `chair_24.jpg` },
    { img: `chair_25.jpg` },
    { img: `chair_26.jpg` },
    { img: `chair_27.jpg` },
    { img: `chair_28.jpg` },
    { img: `chair_29.jpg` },
    { img: `chair_30.jpg` },
    { img: `chair_31.jpg` },
    { img: `chair_32.jpg` },
    { img: `chair_33.jpg` },
    { img: `chair_34.jpg` },
    { img: `chair_35.jpg` },
    { img: `chair_36.jpg` },
    { img: `chair_37.jpg` },
    { img: `chair_38.jpg` },
    { img: `chair_39.jpg` },
    { img: `chair_40.jpg` },
    { img: `chair_41.jpg` },
    { img: `chair_42.jpg` },
    { img: `chair_43.jpg` },
    { img: `chair_44.jpg` },
    { img: `chair_45.jpg` }
  ],
  heading: 'Krzesła i fotele konferencyjne',
  subHeading: 'Produkty'
}
